pixi upload, get anaconda from pixi for pkg-remove

diff --git a/pkg-remove/action.yaml b/pkg-remove/action.yaml
--- a/pkg-remove/action.yaml
+++ b/pkg-remove/action.yaml
@@ -37,17 +37,49 @@ outputs:
 runs:
   using: "composite"
   steps:
+    - name: Ensure anaconda command
+      id: get_command
+      shell: bash
+      run: |
+        if command -v anaconda &>/dev/null; then
+          echo "'anaconda' command is available. Using it for upload."
+          echo "CMD=anaconda" >> $GITHUB_OUTPUT
+        elif pixi run anaconda --version &>/dev/null; then
+          echo "anaconda command is available via pixi. Using 'pixi run anaconda' for upload."
+          echo "CMD=pixi run anaconda" >> $GITHUB_OUTPUT
+        else
+            echo "Checking for 'pixi' command..."
+            if command -v pixi &>/dev/null; then
+              echo "'pixi' command is available but 'anaconda' is not found. Installing anaconda-client..."
+              pixi global install anaconda-client
+              echo "Using 'pixi run anaconda' for upload after installation."
+            echo "CMD=pixi run anaconda" >> $GITHUB_OUTPUT
+            else
+              echo "Neither 'anaconda' command nor 'pixi' is available."
+              echo "Please ensure that anaconda-client is installed and available in PATH or via pixi."
+              exit 1
+            fi
+        fi
     - name: Remove old labeled packages
       id: remove_pkg
       shell: bash
       env:
-        ANACONDA_TOKEN: ${{ inputs.anaconda_token }}
+        ANACONDA_API_TOKEN: ${{ inputs.anaconda_token }}
         ORGANIZATION: ${{ inputs.organization }}
         PACKAGE_NAME: ${{ inputs.package_name }}
         LABEL: ${{ inputs.label }}
         KEEP: ${{ inputs.keep }}
         DRY_RUN: ${{ inputs.dry_run }}
       run: |
+
+        set -euo pipefail
+
+        CMD="${{ steps.get_command.outputs.CMD }}"
+        if [ -z "${CMD}" ]; then
+          echo "No upload command detected from previous step."
+          exit 1
+        fi
+
         ANACONDA_URL="https://api.anaconda.org/package/"
         ANACONDA_URL="${ANACONDA_URL}${{ env.ORGANIZATION }}/${{ env.PACKAGE_NAME }}"
         # 5.5 second timeout on curl
@@ -57,6 +89,7 @@ runs:
           exit 1
         fi
         echo "${RAW_RESULT}"
+
         FILES_TO_REMOVE=$(echo "${RAW_RESULT}" \
           | jq -r '
             [.files[] | select(.labels | index("${{ env.LABEL }}"))]
@@ -74,6 +107,7 @@ runs:
         echo "" # blank line
         echo "dry-run=${{ env.DRY_RUN }}"
         num_removed=0 # count how many files are removed
+
         if [ -z "${FILES_TO_REMOVE}" ]; then
           echo "No old files to remove from ${{ env.LABEL }}"
           # write out number of packages that should have been deleted
@@ -81,8 +115,9 @@ runs:
           echo "Removing old ${{ env.LABEL }} files"
           for FILE in ${FILES_TO_REMOVE}; do
             echo "Removing ${FILE}"
-            if [ "${{ env.DRY_RUN }}" = "false" ]; then
-              pixi run anaconda remove --force "${FILE}"
+            remove_cmd="${CMD} remove --force ${FILE}"
+            if [ "${DRY_RUN}" = "false" ]; then
+              ${remove_cmd}
             fi
             num_removed=$((num_removed+1))
           done
