Split indexer into seperate environment (#4)

diff --git a/pkg-verify/action.yaml b/pkg-verify/action.yaml
--- a/pkg-verify/action.yaml
+++ b/pkg-verify/action.yaml
@@ -1,4 +1,4 @@
-name: conda-verify
+name: pkg-verify
 description: Install and import a conda package with micromamba
 author: glass-ships
 branding:
@@ -6,29 +6,15 @@ branding:
   color: yellow
 
 inputs:
-  local-channel:
-    description: |
-      Local conda channel (path to directory containing .conda file)
-      For example, if the .conda artifact is downloaded to `/tmp/local-channel/linux-64`,
-      this should be set to `/tmp/local-channel`
-    required: false
   package-name:
     description: Name of the package to install and verify
     required: true
   module-name:
     description: Name of the python module, if different from package name
     required: false
-  python-version:
-    description: Python version to use when setting up micromamba
-    required: false
-    default: "3.10"
-  extra-channels:
-    description: |
-      Additional channels to use when installing the package
-      Note, conda-forge is included by default
-      Example:
-        channels: mantid neutrons
-    required: false
+  conda-env-name:
+    description: Name of the conda environment the package is installed in
+    required: true
   extra-commands:
     description: Additional bash commands to be run during the verification step.
     required: false
@@ -36,61 +22,36 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Setup micromamba
-      uses: mamba-org/setup-micromamba@v3
-      with:
-        environment-name: test
-        init-shell: bash
-        create-args: >-
-          python=${{ inputs.python-version }}
-
-    - name: Index local conda channel
-      if: ${{ inputs.local-channel }}
-      shell: bash -el {0}
-      env:
-        LOCAL_CHANNEL: ${{ inputs.local-channel }}
-      run: |
-        echo "Index the local conda channel"
-        micromamba install -y -c conda-forge conda-build conda-index
-        python -m conda_index ${LOCAL_CHANNEL}
-
-    - name: Install the package
-      shell: bash -el {0}
-      env:
-        LOCAL_CHANNEL: ${{ inputs.local-channel }}
-        EXTRA_CHANNELS: ${{ inputs.extra-channels }}
-        PKG_NAME: ${{ inputs.package-name }}
-      run: |
-        echo "Install the conda package"
-        channels="conda-forge"
-        if [ -n "${LOCAL_CHANNEL}" ]; then
-            channels="${LOCAL_CHANNEL} $channels"
-        fi
-
-        if [ -n "${EXTRA_CHANNELS}" ]; then
-            channels+=" ${EXTRA_CHANNELS}"
-        fi
-
-        channels="-c ${channels// / -c }"
-        micromamba install -y ${channels} ${PKG_NAME}
-
     - name: Verify the installation
       shell: bash -el {0}
       env:
         PKG_NAME: ${{ inputs.package-name }}
         MODULE_NAME: ${{ inputs.module-name }}
+        CONDA_TEST_ENV_NAME: ${{ inputs.conda-env-name }}
         EXTRA_COMMANDS: ${{ inputs.extra-commands }}
       run: |
-        echo "Verifying conda package"
+        echo "Verifying conda package in environment '${CONDA_TEST_ENV_NAME}'"
+        micromamba activate ${CONDA_TEST_ENV_NAME}
 
+        # parse package name from list of conda packages
         conda_version=$(micromamba list "${PKG_NAME}" | awk -v pkg="${PKG_NAME}" '$1 == pkg { print $2 }')
+        if [ -z "${conda_version}" ]; then
+          echo "Failed to find version of ${PKG_NAME} from conda environment '${CONDA_TEST_ENV_NAME}'"
+          exit 1
+        fi
 
+        # get package version from list of conda packages
         if [ -n "${MODULE_NAME}" ]; then
           python_version=$(python -c "import ${MODULE_NAME}; print(${MODULE_NAME}.__version__)" | tail -n 1)
         else
           python_version=$(python -c "import ${PKG_NAME}; print(${PKG_NAME}.__version__)" | tail -n 1)
         fi
+        if [ -z "${python_version}" ]; then
+          echo "Failed to find version of ${PKG_NAME} from python module"
+          exit 1
+        fi
 
+        # print simple version results
         echo "------------------------"
         echo "Conda version: $conda_version"
         echo "Python version: $python_version"
@@ -102,8 +63,8 @@ runs:
           echo "Versions match."
         fi
 
+        # print extra results
         echo "------------------------"
-
         if [ -n "${EXTRA_COMMANDS}" ]; then
           echo "Running additional commands:"
           readarray -t commands <<< "${EXTRA_COMMANDS}"
